language: go

go:
  - 1.7
  - tip

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

install:
  - go get -t -d -v ./...

script:
  - go test -v -race ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
